### ISSUE TITLE
After running msgmerge-female english.pot and *.po files have extra "\." added for every file.

### ISSUE THREAD

**Issue by ALIENQuake** [BGforgeNet/msg2po#4]
Hi,

![S6Rib7T 1](https://github.com/BGforgeNet/msg2po/assets/365255/db3603b6-5d88-426f-bf6c-30998599eda0)

Execution logs:
```
PS C:\Users\ALIEN\Documents\GitHub\Ascension>  python C:\Users\ALIEN\Downloads\msg2po\msg2po\poify.py
Found directory ascension/lang\english
processing .\ascension.tra with encoding cp1252
processing .\balth.tra with encoding cp1252
processing .\balth_finsol.tra with encoding cp1252
processing .\bodhi_solar.tra with encoding cp1252
processing .\description.tra with encoding cp1252
processing .\dream_mel.tra with encoding cp1252
processing .\dream_solar.tra with encoding cp1252
processing .\epilogues.tra with encoding cp1252
processing .\imoen_after.tra with encoding cp1252
processing .\iren_bodhi.tra with encoding cp1252
processing .\iren_sarev.tra with encoding cp1252
processing .\items-ee.tra with encoding cp1252
processing .\mel_balth.tra with encoding cp1252
processing .\mel_banter.tra with encoding cp1252
processing .\mel_immortal.tra with encoding cp1252
processing .\mel_initial.tra with encoding cp1252
processing .\mel_iren_imoen.tra with encoding cp1252
processing .\pool_banter.tra with encoding cp1252
processing .\pool_powers.tra with encoding cp1252
processing .\sarevok_sword.tra with encoding cp1252
processing .\setup.tra with encoding cp1252
processing .\shawnesepilogues.tra with encoding cp1252
processing .\shawnesepilogues_eenpc.tra with encoding cp1252
processing .\slayer_dialog.tra with encoding cp1252
processing .\the_five.tra with encoding cp1252
processing .\tougher.tra with encoding cp1252
Processed directory ascension/lang\english, the result is in ascension\lang/po/english.pot
PS C:\Users\ALIEN\Documents\GitHub\Ascension> msgmerge-female
Merging PO files in ascension/lang\po with ascension/lang\po\english.pot
ascension/lang\po\czech.po
ascension/lang\po\german.po
ascension/lang\po\french.po
ascension/lang\po\italian.po
ascension/lang\po\russian.po
ascension/lang\po\polish.po
ascension/lang\po\pt_BR.po
ascension/lang\po\spanish.po
ascension/lang\po\schinese.po
ascension/lang\po\sv.po
ascension/lang\po\tchinese.po






















PS C:\Users\ALIEN\Documents\GitHub\Ascension>
```

**Comment by burner1024** [comment]
Is that PO or POT on screenshot?
Run one command at a time, and see where does it first appear.

**Comment by ALIENQuake** [comment]
It seems that running
```
C:\Users\ALIEN\Documents\GitHub\Ascension>  python C:\Users\ALIEN\Downloads\msg2po\msg2po\poify.py
```
will add an extra `\.` into `english.pot`.

**Comment by burner1024** [comment]
So it's poify, not msgmerge-female.
It does't happen on Linux, and unfortunately I don't have windows to test on. I'll take a look.

**Comment by ALIENQuake** [comment]
Yes, it's poify. My bet is the relative/current dir problem. If I would be able to run poify as exe directly from the working directory, I assume that it won't happen.

**Comment by burner1024** [comment]
You should be able to run it from current directory in dev version. With virtual environment, of course.

**Comment by ALIENQuake** [comment]
Installed msg2po from dev:
```
Successfully built msg2po
Installing collected packages: msg2po
  Attempting uninstall: msg2po
    Found existing installation: msg2po 1.1.12
    Uninstalling msg2po-1.1.12:
      Successfully uninstalled msg2po-1.
1.12
Successfully installed msg2po-1.1.13
```
launched directly:
```
PS C:\Users\ALIEN\Documents\GitHub\Ascension> poify
Found directory ascension/lang\english
processing .\ascension.tra with encoding cp1252
processing .\balth.tra with encoding cp1252
processing .\balth_finsol.tra with encoding cp1252
processing .\bodhi_solar.tra with encoding cp1252
processing .\description.tra with encoding cp1252
processing .\dream_mel.tra with encoding cp1252
processing .\dream_solar.tra with encoding cp1252
processing .\epilogues.tra with encoding cp1252
processing .\imoen_after.tra with encoding cp1252
processing .\iren_bodhi.tra with encoding cp1252
processing .\iren_sarev.tra with encoding cp1252
processing .\items-ee.tra with encoding cp1252
processing .\mel_balth.tra with encoding cp1252
processing .\mel_banter.tra with encoding cp1252
processing .\mel_immortal.tra with encoding cp1252
processing .\mel_initial.tra with encoding cp1252
processing .\mel_iren_imoen.tra with encoding cp1252
processing .\pool_banter.tra with encoding cp1252
processing .\pool_powers.tra with encoding cp1252
processing .\sarevok_sword.tra with encoding cp1252
processing .\setup.tra with encoding cp1252
processing .\shawnesepilogues.tra with encoding cp1252
processing .\shawnesepilogues_eenpc.tra with encoding cp1252
processing .\slayer_dialog.tra with encoding cp1252
processing .\the_five.tra with encoding cp1252
processing .\tougher.tra with encoding cp1252
No change in source directory ascension/lang\english
PS C:\Users\ALIEN\Documents\GitHub\Ascension>
```
and the results are the same: an extra `\.` is added into english.pot

**Comment by burner1024** [comment]
This should fix it (dev2 branch).
Overall, path situation is messy, and this is a temporary bandaid until it can be overhauled properly.

**Comment by ALIENQuake** [comment]
dev2 gives me error:
```
PS C:\Users\ALIEN\Documents\GitHub\Ascension> poify
Found directory ascension/lang\english
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ALIEN\AppData\Local\Programs\Python\Python311\Scripts\poify.exe\__main__.py", line 7, in <module>
  File "C:\Users\ALIEN\AppData\Local\Programs\Python\Python311\Lib\site-packages\msg2po\poify.py", line 151, in main
    poify(poify_dir)
  File "C:\Users\ALIEN\AppData\Local\Programs\Python\Python311\Lib\site-packages\msg2po\poify.py", line 74, in poify
    full_name = re.sub("\\", "/", full_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ALIEN\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ALIEN\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ALIEN\AppData\Local\Programs\Python\Python311\Lib\re\_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ALIEN\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 973, in parse
    source = Tokenizer(str)
             ^^^^^^^^^^^^^^
  File "C:\Users\ALIEN\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 230, in __init__
    self.__next()
  File "C:\Users\ALIEN\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 243, in __next
    raise error("bad escape (end of pattern)",
re.error: bad escape (end of pattern) at position 0
```

**Comment by burner1024** [comment]
How about now?

**Comment by ALIENQuake** [comment]
Now it's fixed, I no longer see modified english.pot:
```
PS C:\Users\ALIEN\Documents\GitHub\Ascension> poify
Found directory ascension/lang\english
processing ascension.tra with encoding cp1252
processing balth.tra with encoding cp1252
processing balth_finsol.tra with encoding cp1252
processing bodhi_solar.tra with encoding cp1252
processing description.tra with encoding cp1252
processing dream_mel.tra with encoding cp1252
processing dream_solar.tra with encoding cp1252
processing epilogues.tra with encoding cp1252
processing imoen_after.tra with encoding cp1252
processing iren_bodhi.tra with encoding cp1252
processing iren_sarev.tra with encoding cp1252
processing items-ee.tra with encoding cp1252
processing mel_balth.tra with encoding cp1252
processing mel_banter.tra with encoding cp1252
processing mel_immortal.tra with encoding cp1252
processing mel_initial.tra with encoding cp1252
processing mel_iren_imoen.tra with encoding cp1252
processing pool_banter.tra with encoding cp1252
processing pool_powers.tra with encoding cp1252
processing sarevok_sword.tra with encoding cp1252
processing setup.tra with encoding cp1252
processing shawnesepilogues.tra with encoding cp1252
processing shawnesepilogues_eenpc.tra with encoding cp1252
processing slayer_dialog.tra with encoding cp1252
processing the_five.tra with encoding cp1252
processing tougher.tra with encoding cp1252
No change in source directory ascension/lang\english
PS C:\Users\ALIEN\Documents\GitHub\Ascension>
```
